services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartlearn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      

  app:
    image: backend
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      DB_HOST: mysql_db
    volumes:
      - names-volumes:/app
volumes:
  names-volumes:
  mysql-data:
