spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_db}:${3306}/${DB_NAME:smartlearn}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: ${SERVER_PORT:9090}
app:
  file:
    path: ./names.txt