spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
 
  h2:
    console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:9090}
app:
  file:
    path: ./names.txt